---name: Demo Appdescription: >
  A Demo App which does almost nothing of any practical value.
version: '2' 
category: tracy_app 
maintainer: tracy <tracy@rancher.com|2353912151@qq.com>
license: Apache2
projectURL: https://github.com/Tracy1994/wordpressCatalo
