name: #wordpress App
description: |
  # A wordpress App.
version: # Version of the Catalog to be used 
category: # Category to be used for searching catalog entries
maintainer: # The maintainer of the catalog entry
license: # The license
URL: # A URL related to the catalog entry
